const Dropdowns = {
    sex: {
        'Male': 'male',
        'Female': 'female',
        'Other': 'other',
        'Prefer not to say': 'no-response',
    } as Record<string, string>,
    language: {
        'English': 'en',
        'Spanish': 'es',
        'French': 'fr',
        'German': 'de',
        'Italian': 'it',
        'Portuguese': 'pt',
        'Russian': 'ru',
        'Japanese': 'ja',
        'Korean': 'ko',
        'Chinese (Simplified)': 'zh-cn',
        'Chinese (Traditional)': 'zh-tw',
        'Arabic': 'ar',
        'Hindi': 'hi',
        'Dutch': 'nl',
        'Polish': 'pl',
        'Turkish': 'tr',
        'Swedish': 'sv',
        'Indonesian': 'id',
        'Vietnamese': 'vi',
        'Thai': 'th',
        'Prefer not to say': 'no-response',
    } as Record<string, string>,
    appointmentType: {
        'New Patient': 'new-patient',
        'Specialist': 'specialist',
        'Consultation': 'consultation',
        'Follow-Up': 'follow-up',
        'Annual Physical': 'annual-physical',
        'Urgent Concern': 'urgent-concern',
        'Telehealth': 'telehealth',
        'Other': 'other',
        'Prefer not to say': 'no-response',
    } as Record<string, string>,
    concernStart: {
        'Today': 'today',
        'Within the Past Week': 'past-week',
        'Within the Past Month': 'past-month',
        '1-3 Months Ago': '1-3-months',
        '3-6 Months Ago': '3-6-months',
        'Over 6 Months Ago': 'over-6-months',
        'Ongoing / Chronic': 'chronic',
        'Unsure': 'unsure',
        'Other': 'other',
        'Prefer not to say': 'no-response',
    } as Record<string, string>,
    concernSeverity: {
        '1 - Very mild (barely noticeable)': '1',
        '2 - Mild (easily ignored)': '2',
        '3 - Noticeable (distracting)': '3',
        '4 - Troublesome (interrupts tasks)': '4',
        '5 - Limits activity': '5',
        '6 - Strong (impairs focus)': '6',
        '7 - Severe (hard to ignore)': '7',
        '8 - Very severe (dominates attention)': '8',
        '9 - Extreme (near unbearable)': '9',
        '10 - Worst (unbearable)': '10',
        'Prefer not to say': 'no-response',
    } as Record<string, string>,
    visitGoal: {
        'Get a Diagnosis': 'get-diagnosis',
        'Adjust Medication': 'adjust-medication',
        'Lifestyle Advice': 'lifestyle-advice',
        'Understand Test Results': 'understand-test-results',
        'Preventive Care Recommendations': 'preventive-care-recommendations',
        'Mental Health Support': 'mental-health-support',
        'Discuss Treatment Options': 'discuss-treatment-options',
        'Plan Future Appointments': 'plan-future-appointments',
        'Other': 'other',
        'Prefer not to say': 'no-response',
    } as Record<string, string>,
    specificWorries: {
        'Pain or Discomfort': 'pain-discomfort',
        'Fatigue or Low Energy': 'fatigue-low-energy',
        'Digestive Issues': 'digestive-issues',
        'Respiratory Issues': 'respiratory-issues',
        'Skin or Hair Changes': 'skin-hair-changes',
        'Mood or Mental Health': 'mood-mental-health',
        'Medication Side Effects': 'medication-side-effects',
        'Lab or Test Results': 'lab-test-results',
        'Preventive Care': 'preventive-care',
        'Other': 'other',
        'Prefer not to say': 'no-response',
    } as Record<string, string>,
    notified: {
        'At time of appointment': '0',
        '5 minutes before': '300',
        '15 minutes before': '900',
        '30 minutes before': '1800',
        '1 hour before': '3600',
        '2 hours before': '7200',
        '1 day before': '86400',
        '2 days before': '172800',
        '1 week before': '604800',
    } as Record<string, string>,
};

export default Dropdowns;
