// Dropdown Labels and Values
export const DropdownValues = {
    sex: [
        { label: 'Male', value: 'male' },
        { label: 'Female', value: 'female' },
        { label: 'Other', value: 'other' },
        { label: 'Prefer not to say', value: 'no-response' },
    ],

    language: [
        { label: 'English', value: 'en' },
        { label: 'Spanish', value: 'es' },
        { label: 'French', value: 'fr' },
        { label: 'German', value: 'de' },
        { label: 'Italian', value: 'it' },
        { label: 'Portuguese', value: 'pt' },
        { label: 'Russian', value: 'ru' },
        { label: 'Japanese', value: 'ja' },
        { label: 'Korean', value: 'ko' },
        { label: 'Chinese (Simplified)', value: 'zh-CN' },
        { label: 'Chinese (Traditional)', value: 'zh-TW' },
        { label: 'Arabic', value: 'ar' },
        { label: 'Hindi', value: 'hi' },
        { label: 'Dutch', value: 'nl' },
        { label: 'Polish', value: 'pl' },
        { label: 'Turkish', value: 'tr' },
        { label: 'Swedish', value: 'sv' },
        { label: 'Indonesian', value: 'id' },
        { label: 'Vietnamese', value: 'vi' },
        { label: 'Thai', value: 'th' },
        { label: 'Prefer not to say', value: 'no-response' },
    ],

    appointmentType: [
        { label: 'New Patient', value: 'new-patient' },
        { label: 'Specialist', value: 'specialist' },
        { label: 'Consultation', value: 'consultation' },
        { label: 'Follow-Up', value: 'follow-up' },
        { label: 'Annual Physical', value: 'annual-physical' },
        { label: 'Urgent Concern', value: 'urgent-concern' },
        { label: 'Telehealth', value: 'telehealth' },
        { label: 'Other', value: 'other' },
        { label: 'Prefer not to say', value: 'no-response' },
    ],

    concernStart: [
        { label: 'Today', value: 'today' },
        { label: 'Within the Past Week', value: 'past-week' },
        { label: 'Within the Past Month', value: 'past-month' },
        { label: '1-3 Months Ago', value: '1-3-months' },
        { label: '3-6 Months Ago', value: '3-6-months' },
        { label: 'Over 6 Months Ago', value: 'over-6-months' },
        { label: 'Ongoing / Chronic', value: 'chronic' },
        { label: 'Unsure', value: 'unsure' },
        { label: 'Other', value: 'other' },
        { label: 'Prefer not to say', value: 'no-response' },
    ],

    concernSeverity: [
        { label: '1 - Very Mild', value: '1' },
        { label: '2', value: '2' },
        { label: '3', value: '3' },
        { label: '4', value: '4' },
        { label: '5 - Moderate', value: '5' },
        { label: '6', value: '6' },
        { label: '7', value: '7' },
        { label: '8', value: '8' },
        { label: '9', value: '9' },
        { label: '10 - Severe / Worst Pain', value: '10' },
        { label: 'Prefer not to say', value: 'no-response' },
    ],

    visitGoal: [
        { label: 'Get a Diagnosis', value: 'get-diagnosis' },
        { label: 'Adjust Medication', value: 'adjust-medication' },
        { label: 'Lifestyle Advice', value: 'lifestyle-advice' },
        { label: 'Understand Test Results', value: 'understand-test-results' },
        { label: 'Preventive Care Recommendations', value: 'preventive-care-recommendations' },
        { label: 'Mental Health Support', value: 'mental-health-support' },
        { label: 'Discuss Treatment Options', value: 'discuss-treatment-options' },
        { label: 'Plan Future Appointments', value: 'plan-future-appointments' },
        { label: 'Other', value: 'other' },
        { label: 'Prefer not to say', value: 'no-response' },
    ],

    specificWorries: [
        { label: 'Pain or Discomfort', value: 'pain-discomfort' },
        { label: 'Fatigue or Low Energy', value: 'fatigue-low-energy' },
        { label: 'Digestive Issues', value: 'digestive-issues' },
        { label: 'Respiratory Issues', value: 'respiratory-issues' },
        { label: 'Skin or Hair Changes', value: 'skin-hair-changes' },
        { label: 'Mood or Mental Health', value: 'mood-mental-health' },
        { label: 'Medication Side Effects', value: 'medication-side-effects' },
        { label: 'Lab or Test Results', value: 'lab-test-results' },
        { label: 'Preventive Care', value: 'preventive-care' },
        { label: 'Other', value: 'other' },
        { label: 'Prefer not to say', value: 'no-response' },
    ],

    notified: [
        { label: 'At time of appointment', value: '0' },
        { label: '5 minutes before', value: '300' },
        { label: '15 minutes before', value: '900' },
        { label: '30 minutes before', value: '1800' },
        { label: '1 hour before', value: '3600' },
        { label: '2 hours before', value: '7200' },
        { label: '1 day before', value: '86400' },
        { label: '2 days before', value: '172800' },
        { label: '1 week before', value: '604800' },
    ],
};
